package org.example;


public class Main {
    public static void main(String[] args) { // Not Used as actual main
        //Listed as a string here is the bot token generated by the discord dev cite
        String Token = "MTA1MjAyNTU4NzY3MTI0NDgxMA.G1fa0M.Uq2Kd-4BYdG_y3LmsxQaQjBmJR0x298Ce9wiD8";

        //This code only needs to be run once per new command, greyed out is already on the bot and is kept here as a reminder.
        //Does NOT need to be done each time code is run.
            //Has to be kept running for over a minute or so before the Search Bot's command list is updated

        /* Ping Command:
        DiscordApi api = new DiscordApiBuilder().setToken(Token).login().join();

        SlashCommand.with("ping", "A simple ping pong command!").createGlobal(api).join();*/

        /* Disconnect Command:
        DiscordApi api = new DiscordApiBuilder().setToken(Token).login().join();

        SlashCommand.with("disconnect", "A command to disconnect this bot.").createGlobal(api).join();*/

        /* Google Search Command:
        DiscordApi api = new DiscordApiBuilder().setToken(Token).login().join();

        List<SlashCommandOption> query = new ArrayList<SlashCommandOption>();
         query.add (SlashCommandOption.create(SlashCommandOptionType.STRING, "query", "What you want to search", true));

        SlashCommand.with("search", "A simple google search command", query).createGlobal(api).join();*/

        /* Google Search Command:
        DiscordApi api = new DiscordApiBuilder().setToken(Token).login().join();

        List<SlashCommandOption> query = new ArrayList<SlashCommandOption>();
         query.add (SlashCommandOption.create(SlashCommandOptionType.STRING, "query", "What wiki cite you want to search for", true));

        SlashCommand.with("searchwiki", "A Wikipedia search command", query).createGlobal(api).join();*/



    }
}